# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialogs\remove_plugin_dialog\remove_plugin_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(316, 221)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("dialogs\\remove_plugin_dialog\\../../images/icons/remove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("background-color: #0d1117;\n"
"font: 25px \"Verdana\";\n"
"")
        self.hint = QtWidgets.QLabel(Dialog)
        self.hint.setGeometry(QtCore.QRect(20, 70, 301, 31))
        self.hint.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    font-size: 15px;\n"
"}")
        self.hint.setObjectName("hint")
        self.title = QtWidgets.QLabel(Dialog)
        self.title.setGeometry(QtCore.QRect(20, 20, 231, 41))
        self.title.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    font-size: 30px;\n"
"}")
        self.title.setObjectName("title")
        self.remove = QtWidgets.QPushButton(Dialog)
        self.remove.setGeometry(QtCore.QRect(220, 110, 35, 35))
        self.remove.setStyleSheet("QPushButton {\n"
"    border: 0px;\n"
"    color: white;\n"
"    font: 25px \"Verdana\";\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background-color: #5a6677;\n"
"}\n"
"")
        self.remove.setText("")
        self.remove.setIcon(icon)
        self.remove.setIconSize(QtCore.QSize(30, 30))
        self.remove.setObjectName("remove")
        self.cancel = QtWidgets.QPushButton(Dialog)
        self.cancel.setGeometry(QtCore.QRect(260, 110, 35, 35))
        self.cancel.setStyleSheet("QPushButton {\n"
"    border: 0px;\n"
"    color: white;\n"
"    font: 25px \"Verdana\";\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background-color: #5a6677;\n"
"}\n"
"")
        self.cancel.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("dialogs\\remove_plugin_dialog\\../../images/icons/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cancel.setIcon(icon1)
        self.cancel.setIconSize(QtCore.QSize(30, 30))
        self.cancel.setObjectName("cancel")
        self.plugin_input = QtWidgets.QComboBox(Dialog)
        self.plugin_input.setGeometry(QtCore.QRect(20, 112, 191, 31))
        self.plugin_input.setStyleSheet("QComboBox {\n"
"    background-color: white;\n"
"    border-radius: 10px;\n"
"    font-size: 17px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border-radius: 10px;\n"
"}")
        self.plugin_input.setObjectName("plugin_input")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Remove plugin"))
        self.hint.setText(_translate("Dialog", "Select plugin"))
        self.title.setText(_translate("Dialog", "Remove plugin"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
